### PR TITLE
propose questions mdbook could probably answer

### PR DESCRIPTION
**Pull request by shamrin**
This is a reply to PR #69:

> Importantly, I would be delighted to accept pull requests on the SUMMARY.md file outlining the structure of the book, as a way of requesting topics. I will be filling things in as they come to me, or as they seem important, but this is a great way to communicate that you'd like a particular area explained.

This PR shouldn't be merged. It's simply a way to ask questions about timely dataflow.

### CODE REVIEW

**Comment by frankmcsherry** [comment]
These are good points! I forget that not everyone is a high-throughput data junkie, and may have other goals in programming, life. :)

**Comment by frankmcsherry** [comment]
I've pushed some more content of this form. Ideally this would cause this PR to break (because I've tweaked `SUMMARY.md`, but let's see. I suppose the protocol is "close the issue if you find the material fills the intended role". If it nearly does but misses some important features (e.g. I think maybe I should explain the "problems solved" as "managing scheduling, distribution, and serialization" rather than "computational finance" or "biology").

**Comment by shamrin** [comment]
:1st_place_medal: 

Wow, awesome! I haven't finished reading it yet, but it looks like you've answered my questions perfectly. I'll do more GitHub pokes if I find anything.

**Comment by shamrin** [comment]
I've created issue #86 about the things I've found difficult and the things I've found helpful.

**Pull request closed without merging**
