### PR TITLE
Flow-controlled source operator

### PR DESCRIPTION
**Pull request by utaal**

### CODE REVIEW

**Comment by utaal** [comment]
Take 2, based (in part) on offline brainstorming.

**Comment by utaal** [comment]
Take 3! (This one more geared towards flow-control)

**Comment by utaal** [comment]
Now generates input as `IntoIterator<Item=(T, IntoIterator<Item=D>)>` to avoid re-opening the same session over and over.

**Comment by frankmcsherry** [comment]
This looks good to me.

**Pull request merged**
